using System.Collections;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Singleton manager for screen transitions (Fade to Black / Fade from Black).
/// Auto-creates a full-screen Canvas overlay if one is not present in the scene.
/// </summary>
public class ScreenFader : MonoBehaviour
{
    private static ScreenFader instance;
    public static ScreenFader Instance
    {
        get
        {
            if (instance == null)
            {
                instance = FindFirstObjectByType<ScreenFader>();
                if (instance == null)
                {
                    GameObject faderGO = new GameObject("ScreenFader_AutoGenerated");
                    instance = faderGO.AddComponent<ScreenFader>();
                    DontDestroyOnLoad(faderGO);
                }
            }
            return instance;
        }
    }

    [Header("UI References (Auto-created if null)")]
    [SerializeField] private Canvas fadeCanvas;
    [SerializeField] private CanvasGroup fadeCanvasGroup;
    [SerializeField] private Image fadeImage;

    [Header("Default Fade Color")]
    [SerializeField] private Color fadeColor = Color.black;

    private void Awake()
    {
        if (instance != null && instance != this)
        {
            Destroy(gameObject);
            return;
        }
        instance = this;
        DontDestroyOnLoad(gameObject);

        EnsureUIComponents();
    }

    /// <summary>
    /// Ensures UI Canvas, Image, and CanvasGroup exist and are configured.
    /// </summary>
    private void EnsureUIComponents()
    {
        if (fadeCanvas == null)
        {
            fadeCanvas = GetComponentInChildren<Canvas>();
        }

        if (fadeCanvas == null)
        {
            GameObject canvasGO = new GameObject("FadeCanvas");
            canvasGO.transform.SetParent(transform, false);

            fadeCanvas = canvasGO.AddComponent<Canvas>();
            fadeCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
            fadeCanvas.sortingOrder = 999; // Topmost sorting order

            canvasGO.AddComponent<CanvasScaler>();
            canvasGO.AddComponent<GraphicRaycaster>();
        }

        if (fadeCanvasGroup == null)
        {
            fadeCanvasGroup = fadeCanvas.GetComponent<CanvasGroup>();
            if (fadeCanvasGroup == null)
            {
                fadeCanvasGroup = fadeCanvas.gameObject.AddComponent<CanvasGroup>();
            }
        }

        if (fadeImage == null)
        {
            fadeImage = fadeCanvas.GetComponentInChildren<Image>();
            if (fadeImage == null)
            {
                GameObject imageGO = new GameObject("FadeImage");
                imageGO.transform.SetParent(fadeCanvas.transform, false);

                fadeImage = imageGO.AddComponent<Image>();
                RectTransform rect = fadeImage.rectTransform;
                rect.anchorMin = Vector2.zero;
                rect.anchorMax = Vector2.one;
                rect.offsetMin = Vector2.zero;
                rect.offsetMax = Vector2.one;
            }
        }

        fadeImage.color = fadeColor;
        fadeCanvasGroup.alpha = 0f;
        fadeCanvasGroup.blocksRaycasts = false;
        fadeCanvasGroup.interactable = false;
    }

    /// <summary>
    /// Fades the screen from transparent to black (Fade Out).
    /// </summary>
    public IEnumerator FadeOutRoutine(float duration = 0.5f)
    {
        EnsureUIComponents();
        fadeCanvasGroup.blocksRaycasts = true;

        float timer = 0f;
        float startAlpha = fadeCanvasGroup.alpha;

        while (timer < duration)
        {
            timer += Time.deltaTime;
            fadeCanvasGroup.alpha = Mathf.Lerp(startAlpha, 1f, timer / duration);
            yield return null;
        }

        fadeCanvasGroup.alpha = 1f;
    }

    /// <summary>
    /// Fades the screen from black to transparent (Fade In).
    /// </summary>
    public IEnumerator FadeInRoutine(float duration = 0.5f)
    {
        EnsureUIComponents();

        float timer = 0f;
        float startAlpha = fadeCanvasGroup.alpha;

        while (timer < duration)
        {
            timer += Time.deltaTime;
            fadeCanvasGroup.alpha = Mathf.Lerp(startAlpha, 0f, timer / duration);
            yield return null;
        }

        fadeCanvasGroup.alpha = 0f;
        fadeCanvasGroup.blocksRaycasts = false;
    }

    /// <summary>
    /// Full screen transition helper: Fade Out -> Execute Callback (teleport/load scene) -> Wait -> Fade In.
    /// </summary>
    public IEnumerator FadeTransitionRoutine(float fadeOutDuration, float blackoutHoldTime, float fadeInDuration, System.Action onBlackoutAction)
    {
        yield return StartCoroutine(FadeOutRoutine(fadeOutDuration));

        onBlackoutAction?.Invoke();

        if (blackoutHoldTime > 0f)
        {
            yield return new WaitForSeconds(blackoutHoldTime);
        }

        yield return StartCoroutine(FadeInRoutine(fadeInDuration));
    }
}
